name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test imports
      run: |
        python -c "
        import sys
        sys.path.insert(0, '.')
        try:
            from cortex.core import CortexAgent
            from cortex.modules import CodeGenerator, ImageGenerator, VideoGenerator
            print('✅ All imports successful')
        except ImportError as e:
            print(f'❌ Import error: {e}')
            exit(1)
        "

    - name: Test basic functionality
      run: |
        python -c "
        import sys
        sys.path.insert(0, '.')
        from app import HuggingFaceGradioDeployment
        
        # Test initialization
        deployment = HuggingFaceGradioDeployment()
        print('✅ Deployment initialized successfully')
        
        # Test system info
        info = deployment.get_system_info()
        print('✅ System info generated')
        
        print('✅ Basic functionality test passed')
        "

    - name: Deploy to Hugging Face Spaces
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git config --global user.name "Cortex Codegen"
        git config --global user.email "cortex-codegen@agent.ai"
        git remote set-url origin https://CortexCodegen:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/alex10007/cortex-codegen
        git push origin main